name: Keep Alive

on:
  schedule:
    - cron: '*/25 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -s https://sem-cathode-analyzer.streamlit.app/ > /dev/null